spring:
    application:
      name: bankingapp-registry-service
    cloud:
      config:
        discovery:
          enabled: true
          service-id: bankingapp-config-server

    config:
      import: "optional:configserver:"
#server:
#    port: 8761
#
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
#    register-with-eureka: false
#    fetch-registry: false
