spring:
  application:
    name: bankingapp-transaction-service
  datasource:
    url: jdbc:postgresql://${DB}:5432/bankingapp-transaction-service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
#  h2:
#    console:
#      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVERS}

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_HOST}/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"