spring:
  application:
    name: bankingapp-fund-transfer-service
  datasource:
    url: jdbc:postgresql://${DB}:5432/bankingapp-fund-transfer-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVERS}

server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_HOST}/eureka
    register-with-eureka: true
    fetch-registry: false

bankingapp:
  kafka:
    topic:
      fund-transfers: fund-transfers
      transaction: transactions


management:
  endpoints:
    web:
      exposure:
        include: "*"