spring:
  application:
    name: bankingapp-account-service
  datasource:
    url: jdbc:postgresql://db:5432/bankingapp-account-service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
#    h2:
#      console:
#        enabled: true
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://bankingapp-registry-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

bankingapp:
  kafka:
    topic:
      fund-transfers: status

management:
  endpoints:
    web:
      exposure:
        include: "*"